[package]
name = "solana-rpc-get-stake-activation"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = "1"
solana-rpc-client = "2.0.3"
solana-rpc-client-api = "2.0.3"
solana-sdk = "2.0.3"

[[example]]
name = "rpc"
